### ISSUE TITLE
Install Essential Dependencies & Configure TypeScript Paths

### ISSUE THREAD

**Issue by faid-terence** [atlp-rwanda/knights-ecomm-fe#2]
### Description

I need to install essential libraries and set up path aliases to ensure the project setup is efficient, maintainable, and follows best practices. This will streamline the development process and improve code quality by enabling cleaner and more manageable imports.

### Acceptance Criteria
Library Installation
The following libraries are installed:

- [x] react-router-dom
- [x] axios
- [x] redux
- [x] react-redux
- [x] @reduxjs/toolkit
- [x] eslint
- [x] prettier
- [x] vite
- [x] vitest
- [x] @testing-library/react
- [x] @testing-library/jest-dom
- [x] Path Aliases
- [x] Path aliases are configured in vite.config.js for cleaner and more manageable imports.

Definition of Done

- [x] All specified libraries are installed.
- [x] Path aliases are correctly configured.
- [x] The project builds and runs without errors.
- [x] All imported modules use the new path aliases. 

### Implementation Plan

Install Libraries:

 - Copy code 
> `npm install react-router-dom axios redux react-redux @reduxjs/toolkit eslint prettier vite vitest @testing-library/react @testing-library/jest-dom`

- Configure Path Aliases
- Set Up ESLint and Prettier
